Replace one use of JS string `+` with template literal
UMM-CSci-3601/3601-iteration-template pull request #874
Opened 2022-04-22 20:29 UTC by NicMcPhee

I'm just using VS Code's global search tool to look for +s in JS/TS code, and then convert them to use template literals.

The Karma tests didn't fail if I broke many of these, but the E2E tests did, which was nice since I forgot to switch to backticks at least once and actually broke things. The tests caught it, though, and I think this is good now.

2022-04-26 19:59 UTC, helloworld12321 requested changes
I'd suggest one letter case change, but otherwise looks great, thanks! 🙂

2022-04-26 19:59 UTC, helloworld12321 commented on client/src/app/users/add-user.component.ts
> +        `Added User ${this.addUserForm.value.name}`,
Thoughts on lowercase here?

```suggestion
        `Added user ${this.addUserForm.value.name}`,
```

2022-04-28 23:05 UTC, helloworld12321 approved these changes
LGTM! (Although you may need to re-run Cypress)

2022-04-28 23:37 UTC, NicMcPhee commented
Poop – I'm pretty sure this actually breaks the test, which I'm guessing has that text (with the "wrong" case) hardwired in. Doh!

I'll fix that and equest a re-review.

2022-04-29 06:11 UTC, helloworld12321 approved these changes

2022-05-01 02:01 UTC, merged